{
 "title": "Namada Validator/Node Dashboard",
 "description": "By \"AM Solutions\"",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "name",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"},nodename)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$name\"},instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(node_uname_info{instance=~\"$node:(.*)\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Validator Missed Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(namada_tm_consensus_validator_missed_blocks{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"}[5m])",
     "legendFormat": "5 min"
    },
    {
     "expr": "rate(namada_tm_consensus_validator_missed_blocks{chain_id=\"public-testnet-15.0dacadb8d663\"}[6h])",
     "legendFormat": "6 hrs"
    }
   ]
  },
  {
   "title": "Voting Power Missed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_validator_missed_blocks{chain_id=\"public-testnet-15.0dacadb8d663\", instance=\"$node:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node:$port\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voting Power Tendency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(namada_tm_consensus_validator_power{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"})/1000000",
     "legendFormat": "{{validator_address}}"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(namada_tm_consensus_validator_power{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"})/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_height{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Chain Height Flow",
   "type": "timeseries",
   "description": "consensus height",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "namada_tm_consensus_height{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Validators (Active)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_validators{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers Connected",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namada_tm_p2p_peers{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"}",
     "legendFormat": "Peers Tendency"
    }
   ]
  },
  {
   "title": "Peers Connected",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_p2p_peers{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voting Power Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(namada_tm_consensus_validators_power{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"})/1000000",
     "legendFormat": "Voting Power Total"
    }
   ]
  },
  {
   "title": "Total TX`s",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_total_txs{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Transactons flow",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namada_tm_consensus_num_txs{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Recheked TX's",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_mempool_recheck_times{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"} ",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Uncommitted transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_mempool_size{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"}",
     "legendFormat": "Uncommitted transactions"
    }
   ]
  },
  {
   "title": "Block Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namada_tm_consensus_block_size_bytes{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"}",
     "legendFormat": "Block Size (Bytes)"
    }
   ]
  },
  {
   "title": "P2P Kilobytes sent TOTAL",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(namada_tm_p2p_peer_send_bytes_total{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"}[5m])) / 1000",
     "legendFormat": "Outbound traffic"
    }
   ]
  },
  {
   "title": "P2P Kilobytes received TOTAL",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(namada_tm_p2p_peer_receive_bytes_total{chain_id=\"public-testnet-15.0dacadb8d663\",instance=\"$node:26660\"}[5m])) / 1000",
     "legendFormat": "Inbound  traffic"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))",
     "legendFormat": "Uncommitted transactions"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}) / (node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}